### ISSUE TITLE
Playbook fails with " UserWarning: Unknown ssh-ed25519 host key for..."

### ISSUE THREAD

**Issue by ruslaniv** [rywillia/ansible-ssh-copy-id#9]
Hi! 
I have the following role basically copied from the example: 

```
- name: configure passwordless ssh authentication on a remote machine
  hosts: localhost
  roles:
    - role: ryankwilliams.ssh_copy_id
      vars:
        hostname: 192.168.1.118
        username: root
        password: password123
        ssh_public_key: /Users/ruslan/.ssh/centos7vm
        ssh_port: 22
```

when I run the playbook with 

`ansible-playbook ssh.yml -vvv
`
it fails with 

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/Users/ruslan/.local/share/virtualenvs/python_sandbox-Gft-eqT9/lib/python3.9/site-packages/paramiko/client.py:835: UserWarning: Unknown ssh-ed25519 host key for [192.168.1.118]:22: b'736152a766a9c0987ff3a47e1c2c6c92'\n  warnings.warn(\nTraceback (most recent call last):\n  File \"/Users/ruslan/.ansible/tmp/ansible-tmp-1623755639.1153889-50747-125338263348372/AnsiballZ_ssh_copy_id.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/ruslan/.ansible/tmp/ansible-tmp-1623755639.1153889-50747-125338263348372/AnsiballZ_ssh_copy_id.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/ruslan/.ansible/tmp/ansible-tmp-1623755639.1153889-50747-125338263348372/AnsiballZ_ssh_copy_id.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.ssh_copy_id', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/b4/z17ymhcj6q5ffgcqdh_v9jx40000gn/T/ansible_ssh_copy_id_payload_hpyd5aft/ansible_ssh_copy_id_payload.zip/ansible/modules/ssh_copy_id.py\", line 220, in <module>\n  File \"/var/folders/b4/z17ymhcj6q5ffgcqdh_v9jx40000gn/T/ansible_ssh_copy_id_payload_hpyd5aft/ansible_ssh_copy_id_payload.zip/ansible/modules/ssh_copy_id.py\", line 216, in main\n  File \"/var/folders/b4/z17ymhcj6q5ffgcqdh_v9jx40000gn/T/ansible_ssh_copy_id_payload_hpyd5aft/ansible_ssh_copy_id_payload.zip/ansible/modules/ssh_copy_id.py\", line 165, in run_module\nUnboundLocalError: local variable 'auth_key' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
How can I troubleshoot this issue?
